language: python
python:
  - "2.7"
  - "3.6"

git:
  submodules: false # no need to check out MOM6 for now

install:
  - chmod ugo+x ./tests/check_default_params.py
  - pip install pyyaml
  - pip install yamllint

script: 
  - ./tests/check_default_params.py
  - ./tests/doctests.py
  - yamllint param_templates/*.y*ml -c tests/yamllint_config.yaml

