#!/bin/bash

### Job Name
#PBS -N MARBL_test

### Project code
#PBS -A P93300070
#PBS -l walltime=01:00:00
#PBS -q develop

### Merge output and error files
#PBS -j oe
#PBS -k eod

### Select 1 nodes with 1 CPU (a single MPI process)
#PBS -l select=1:ncpus=1:mpiprocs=1

### Send email on abort, begin and end
#PBS -m abe

### Run the executable
../../../build/intel-derecho/MOM6/MOM6
