#!/usr/bin/env python

"""
build mom library
"""
import sys, os, time, filecmp, shutil, imp, glob

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")

_LIBDIR = os.path.join(_CIMEROOT, "scripts", "Tools")
sys.path.append(_LIBDIR)

from standard_script_setup import *
from CIME.buildlib import parse_input
from CIME.case import Case
from CIME.utils import run_cmd, expect
from CIME.build import get_standard_makefile_args

logger = logging.getLogger(__name__)

###############################################################################
def buildlib(caseroot, libroot, bldroot):
###############################################################################

    with Case(caseroot) as case:
        # first check for the external FMS library and build it
        srcroot = case.get_value("SRCROOT")
        fmsbuildlib = os.path.join(srcroot,"libraries","FMS","buildlib")
        fmsbuilddir = os.path.join(bldroot,"FMS")
        if not os.path.exists(fmsbuildlib):
            #todo: call checkout_externals to get this component
            expect(False, "FMS external not found")
        else:
            stat, _, err = run_cmd("{} {} {} {}".format(fmsbuildlib, bldroot, fmsbuilddir, caseroot), verbose=True)
            expect(stat==0, "FMS build Failed {}".format(err))

        # CVMix source code is brought in as a git submodule (or my manage_externals)
        logger.info("Making sure CVMix code is available...")
        cvmix_srcdir = os.path.join(srcroot,"components","mom","MOM6","pkg","CVMix-src","src","shared")
        # If CVMix is not found, abort
        if not os.path.exists(cvmix_srcdir):
            expect(False, "CVMix external not found")

        # MARBL source code is brought in as a git submodule (or my manage_externals)
        logger.info("Making sure MARBL code is available...")
        marbl_srcdir = os.path.join(srcroot,"components","mom","MOM6","pkg","MARBL","src")
        # If MARBL is not found, abort
        if not os.path.exists(marbl_srcdir):
            expect(False, "MARBL external not found")

        casetools = case.get_value("CASETOOLS")
        gmake_j = case.get_value("GMAKE_J")
        gmake = case.get_value("GMAKE")
        mach = case.get_value("MACH")

        #-------------------------------------------------------
        # create Filepath file for mom
        #-------------------------------------------------------
        sharedlibroot = case.get_value("SHAREDLIBROOT")

        user_incldir = "\"-I{} -I{} -I{}\"".\
                        format(os.path.join(srcroot,"libraries","FMS","src","include"),
                               os.path.join(srcroot,"libraries","FMS","src","mpp","include"),
                               fmsbuilddir)
        filepath_file = os.path.join(bldroot,"Filepath")
        if not os.path.isfile(filepath_file):
#todo: are these needed in mom or only for fms?
            driver = case.get_value("COMP_INTERFACE")+"_driver"
            os.environ["CPPDEFS"] = " -Duse_libMPI -Duse_netCDF -DSPMD"
            paths = [os.path.join(caseroot,"SourceMods","src.mom"),
                     os.path.join(srcroot,"components","mom","MOM6","config_src",driver),
                     os.path.join(srcroot,"components","mom","MOM6","config_src","dynamic"),
                     os.path.join(srcroot,"components","mom","MOM6","src","ALE"),
                     os.path.join(srcroot,"components","mom","MOM6","src","core"),
                     os.path.join(srcroot,"components","mom","MOM6","src","diagnostics"),
                     os.path.join(srcroot,"components","mom","MOM6","src","equation_of_state"),
                     os.path.join(srcroot,"components","mom","MOM6","src","equation_of_state","TEOS10"),
                     os.path.join(srcroot,"components","mom","MOM6","src","framework"),
                     os.path.join(srcroot,"components","mom","MOM6","src","ice_shelf"),
                     os.path.join(srcroot,"components","mom","MOM6","src","initialization"),
                     os.path.join(srcroot,"components","mom","MOM6","src","ocean_data_assim"),
                     os.path.join(srcroot,"components","mom","MOM6","src","ocean_data_assim", "core"),
                     os.path.join(srcroot,"components","mom","MOM6","src","ocean_data_assim", "geoKdTree"),
                     cvmix_srcdir,
                     marbl_srcdir,
                     os.path.join(srcroot,"components","mom","MOM6","src","parameterizations","lateral"),
                     os.path.join(srcroot,"components","mom","MOM6","src","parameterizations","vertical"),
                     os.path.join(srcroot,"components","mom","MOM6","src","tracer"),
                     os.path.join(srcroot,"components","mom","MOM6","src","user")]

            with open(filepath_file, "w") as filepath:
                filepath.write("\n".join(paths))
                filepath.write("\n")
        libfms = os.path.join(bldroot,"FMS","libfms.a")
        if os.path.exists(libfms):
            shutil.copy(libfms, libroot)
            # filenames = glob.glob("*.mod")
            # for filename in filenames:
            #     shutil.copy(filename, os.path.join(libroot,"include"))

        os.chdir(bldroot)

        # build the library
        makefile = os.path.join(casetools, "Makefile")
        complib = os.path.join(libroot,"libocn.a")
        cmd = "{} complib -j {} MODEL=mom COMPLIB={} -f {} USER_INCLDIR={} {}"\
                .format(gmake, gmake_j, complib, makefile, user_incldir, get_standard_makefile_args(case))

        rc, out, err = run_cmd(cmd)
        logger.info("%s: \n\n output:\n %s \n\n err:\n\n%s\n"%(cmd,out,err))
        expect(rc == 0, "Command %s failed with rc=%s" % (cmd, rc))


def _main_func():
    caseroot, libroot, bldroot = parse_input(sys.argv)
    buildlib(caseroot, libroot, bldroot)

###############################################################################

if __name__ == "__main__":
    _main_func()
