from __future__ import print_function
from collections import OrderedDict
import os
import abc

class MOM_RPS(object,):
    """ Base class for MOM6 (R)untime (P)arameter (S)ystem files including:
            - Params files (MOM_input, MOM_override, user_nl_mom)
            - MOM_namelist (input.nml)
            - diag_table
    """

    def __init__(self, input_path, input_format,
                       output_path=None, output_format=None):
        self.input_path = input_path
        self.input_format = input_format
        if output_path:
            self.output_path = output_path
        if output_format:
            self.output_format = output_format

    def _read_json(self):
        import json
        with open(self.input_path) as json_file:
            self._params = json.load(json_file, object_pairs_hook=OrderedDict)

    @abc.abstractmethod
    def check_consistency(self):
        pass


class MOM_Params(MOM_RPS):
    """ Encapsulates data and methods for MOM6 case parameter files with the following formats:
        MOM_input, user_nl, json.
    """

    supported_formats = ["MOM_input", "user_nl", "json"]

    def __init__(self, input_path, input_format):
        MOM_RPS.__init__(self, input_path, input_format)

        if self.input_format not in MOM_Params.supported_formats:
            raise RuntimeError("MOM parameter file format "+file_format+\
                                " not supported")

        if self.input_format == "MOM_input":
            self._read_MOM_input()
        elif self.input_format == "user_nl":
            self._read_user_nl()
        elif self.input_format == "json":
            self._read_json()


    def _read_MOM_input(self):
        #TODO
        pass

    def _read_user_nl(self):
        #TODO
        pass

        # 3. Check consistency
        self._check_json_consistency()

    def _check_json_consistency(self):
        #TODO
        pass

    def write_MOM_input(self, output_path, constraints=dict(), add_params=dict()):
        """ writes a MOM_input file from a given json parameter file in accordance with
            the constraints and additional parameters that are passed. """

        assert self.input_format=="json", "MOM_input file can only be generated from a json file."

        self.constraints = constraints

        # 1. First, determine parameter values for the given constraints of the case

        def _constraint_satisfied(constr_pair):
            " Checks if a given value constraint agrees with the constraints of the case"
            constr_key = constr_pair.split('==')[0].strip()\
                .replace('"','').replace("'","")
            constr_val = constr_pair.split('==')[1].strip()\
                .replace('"','').replace("'","")
            return self.constraints[constr_key] == constr_val

        for module in self._params:
            for var in self._params[module]:

                # list of potential values for this variable.
                value_list = self._params[module][var]["value"]

                # current value for this variable:
                val = None

                for value_constraints in value_list:
                    if value_constraints == "common":
                        val = value_list[value_constraints]

                    # multiple constraint pairs in value_constraints
                    elif ',' in value_constraints:
                        agrees = True
                        for constr_pair in value_constraints.split(','):
                            agrees = agrees and _constraint_satisfied(constr_pair)
                        if agrees:
                            val = value_list[value_constraints]

                    # a single constraint pair in value_constraints:
                    elif '==' in value_constraints:
                        if _constraint_satisfied(value_constraints):
                            val = value_list[value_constraints]

                    # value is to be received from add_params filled by buildnml:
                    elif self._params[module][var]["value"] == "None" and var in add_params:
                         val = add_params[var]

                    else:
                        print(self._params[module][var])
                        print("-----------------")
                        print(add_params)
                        raise RuntimeError("Cannot parse configurations for variable "+var)

                self._params[module][var]['final_val'] = val

        # 2. Now, write MOM_input

        MOM_input_header =\
        """/* WARNING: DO NOT EDIT this file. Any changes you make will be overriden. To make
        changes in MOM6 parameters within CESM framework, use SourceMods or
        user_nl_mom mechanisms.

        This input file provides the adjustable run-time parameters for version 6 of
        the Modular Ocean Model (MOM6), a numerical ocean model developed at NOAA-GFDL.
        Where appropriate, parameters use usually given in MKS units.

        This MOM_input file contains the default configuration for CESM. A full list of
        parameters for this example can be found in the corresponding
        MOM_parameter_doc.all file which is generated by the model at run-time. */\n\n"""

        with open(os.path.join(output_path), 'w') as MOM_input:

            MOM_input.write(MOM_input_header)

            tab = " "*32
            for module in self._params:

                # Begin module block:
                if module != "Global":
                    MOM_input.write("%"+module+"\n")

                for var in self._params[module]:
                    val = self._params[module][var]["final_val"]
                    if val==None:
                        continue

                    # write "variable = value" pair
                    MOM_input.write(var+" = "+str(self._params[module][var]["final_val"])+"\n")

                    # Write the variable description:
                    var_comments = self._params[module][var]["description"].split('\n')
                    if len(var_comments[-1])==0:
                        var_comments.pop()
                    for line in var_comments:
                         MOM_input.write(tab+"! "+line+"\n")
                    MOM_input.write("\n")

                # End module block:
                if module != "Global":
                    MOM_input.write(module+"%\n")

