#!/usr/bin/env python

"""mom6 physics cycle postrun script
"""

import os, shutil, sys

_CIMEROOT = os.environ.get("CIMEROOT")
if _CIMEROOT is None:
    raise SystemExit("ERROR: must set CIMEROOT environment variable")
sys.path.append(os.path.join(_CIMEROOT, "CIME", "Tools"))

from standard_script_setup import *
from CIME.case import Case
from CIME.utils import expect

logger = logging.getLogger(__name__)

###############################################################################
def phys_cycle_postrun(caseroot):
###############################################################################

    ch = logging.StreamHandler(stream=sys.stdout)
    ch.setLevel(logging.INFO)
    logger.addHandler(ch)

    with Case(caseroot, read_only=False) as case:
        mom6_phys_cycle_years_in_cycle = case.get_value("MOM6_PHYS_CYCLE_YEARS_IN_CYCLE")
        expect(mom6_phys_cycle_years_in_cycle is not None,
               "MOM6_PHYS_CYCLE_YEARS_IN_CYCLE should be defined when %s is called" % sys.argv[0])
        if (mom6_phys_cycle_years_in_cycle <= 0):
            return

        # -------------------------------------------------------------------------
        # Determine if model has run the length of MOM6 physics run cycle length
        # -------------------------------------------------------------------------

        run_type    = case.get_value("RUN_TYPE")
        stop_option = case.get_value("STOP_OPTION")
        stop_n      = case.get_value("STOP_N")
        caseroot    = case.get_value("CASEROOT")
        rundir      = case.get_value("RUNDIR")

        mom6_phys_cycle_months_run_since_cycle = case.get_value("MOM6_PHYS_CYCLE_MONTHS_RUN_SINCE_CYCLE")
        mom6_phys_cycle_years_in_cycle         = case.get_value("MOM6_PHYS_CYCLE_YEARS_IN_CYCLE")

        # we know from phys_cycle_prerun that stop_option is either "nmonth*" or "nyear*"

        if stop_option.find("nmonth") == 0:
            mom6_phys_cycle_months_run_since_cycle_new = mom6_phys_cycle_months_run_since_cycle + stop_n
        if stop_option.find("nyear") == 0:
            mom6_phys_cycle_months_run_since_cycle_new = mom6_phys_cycle_months_run_since_cycle + stop_n * 12

        case.set_value("MOM6_PHYS_CYCLE_MONTHS_RUN_SINCE_CYCLE", mom6_phys_cycle_months_run_since_cycle_new)
        logger.info("mom6_phys_cycle_months_run_since_cycle is now %d" % mom6_phys_cycle_months_run_since_cycle_new)

        mom6_phys_cycle_months_in_cycle = mom6_phys_cycle_years_in_cycle * 12
        if mom6_phys_cycle_months_run_since_cycle_new < mom6_phys_cycle_months_in_cycle:
            case.set_value("CONTINUE_RUN", "TRUE")
            case.flush()
            return

        expect(mom6_phys_cycle_months_run_since_cycle_new <= mom6_phys_cycle_months_in_cycle,
               "MOM6_PHYS_CYCLE_MONTHS_RUN_SINCE_CYCLE has overshot MOM6_PHYS_CYCLE_MONTHS_IN_CYCLE=%d"
               % mom6_phys_cycle_months_in_cycle)

        # -------------------------------------------------------------------------
        # Model has run the length of MOM6 physics run cycle length
        # Reset model physics, keeping restart file for tracers to continue to evolve
        # -------------------------------------------------------------------------

        logger.info("resetting model physics")
        case.set_value("CONTINUE_RUN", "FALSE")
        case.set_value("MOM6_PHYS_CYCLE_MONTHS_RUN_SINCE_CYCLE", 0)

        # -------------------------------------------------------------------------
        # Compute new RUN_STARTDATE
        # -------------------------------------------------------------------------

        run_startdate = case.get_value("RUN_STARTDATE")
        yyyy = int(run_startdate[:4])
        yyyy = yyyy + mom6_phys_cycle_years_in_cycle
        run_startdate = "%04d" % yyyy + run_startdate[4:]
        case.set_value("RUN_STARTDATE", run_startdate)

        # -------------------------------------------------------------------------
        # Update CPLHIST ALIGN variables
        # -------------------------------------------------------------------------

        varnames_dict = {
            'DATM_MODE': 'DATM_CPLHIST_YR_ALIGN',
            'DROF_MODE': 'DROF_CPLHIST_YR_ALIGN'
        }
        for mode_varname in varnames_dict:
            if case.get_value(mode_varname) == "CPLHIST":
                align_varname = varnames_dict[mode_varname]
                align_val = case.get_value(align_varname)
                if align_val is not None:
                    align_val = align_val + mom6_phys_cycle_years_in_cycle
                    case.set_value(align_varname, align_val)

        case.flush()

###############################################################################

if __name__ == "__main__":
    expect(len(sys.argv) == 2, "caseroot is a required input argument")
    caseroot = sys.argv[1]
    phys_cycle_postrun(caseroot)
